# Spring Web config
server:
  port: 80
  servlet:
    context-path: /shop_mall_project
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JAVA_FRAMEWORK?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: "Aa12345"
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
  # JPA config
  jpa:
    show-sql: true
    # Hibernate config
    database-platform: org.hibernate.dialect.MySQLDialect
  # Spring MVC config
  mvc:
    view:
      prefix: /
# Logback config
logging:
  level:
    com:
      idv:
        shop_mall_project: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%t] %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%level] [%t] [%line] %msg%n'
  file:
    path: ./